services:
  api-perf-redis:
    image: redis:7
    container_name: api-perf-redis
    ports:
      - "6379:6379"
  mysql:
    image: mysql:8.0
    container_name: api-perf-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: perfdb
      MYSQL_USER: perfuser
      MYSQL_PASSWORD: perfpass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3307:3306"
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
